<a href="https://colab.research.google.com/github/phoumithona/tutorial/blob/master/Pytorch_for_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import torch

# input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

# targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

# convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# weights an biases
# yield_apples  = w11*temp + w12*rainfall + w13*humidity + b1
# yield_oranges = w21*temp + w22*rainfall + w23*humidity + b2
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4049, -0.7341,  0.0313],
        [ 0.3274,  0.3072,  0.2080]], requires_grad=True)
tensor([1.3976, 0.2332], requires_grad=True)


In [13]:
 def model(x):
   return x @ w.t() + b

In [17]:
# generate predictions
preds = model(inputs)
print(preds)
# compare with targets
print(targets)

tensor([[ -75.9924,   53.6566],
        [ -98.0373,   70.3679],
        [-130.3733,   81.9409],
        [ -70.3034,   54.5307],
        [ -94.8151,   66.8706]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [19]:
# MSE loss
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

# compute loss
loss = mse(preds, targets)
print(loss)

tensor(16615.1445, grad_fn=<DivBackward0>)


In [20]:
# compute gradients
loss.backward()
# gradients for weights
print(w)
print(w.grad)

tensor([[-0.4049, -0.7341,  0.0313],
        [ 0.3274,  0.3072,  0.2080]], requires_grad=True)
tensor([[-14137.5029, -16194.8213,  -9772.0000],
        [ -2046.3046,  -2976.6304,  -1725.0134]])


In [21]:
print(b)
print(b.grad)

tensor([1.3976, 0.2332], requires_grad=True)
tensor([-170.1043,  -26.5266])


In [22]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [29]:
# gradient descent optimization algorithm 5 steps:
# 1. generate predictions
preds = model(inputs)
print(preds)
# 2. calculate the loss
loss = mse(preds, targets)
print(loss)
# 3. compute gradients : weights and biases
loss.backward()
print(w.grad)
print(b.grad)
# 4. adjust weights
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)
# 5. reset gradients to zero


tensor([[-25.2433,  62.1170],
        [-31.2926,  81.5396],
        [-51.0330,  95.4803],
        [-20.3007,  62.5421],
        [-30.5271,  77.8252]], grad_fn=<AddBackward0>)
tensor(7193.6514, grad_fn=<DivBackward0>)
tensor([[ -8894.0605, -10549.4023,  -6290.8262],
        [ -1169.2661,  -2024.5562,  -1139.5505]])
tensor([-107.8793,  -16.0991])
tensor([[-0.0332, -0.3047,  0.2897],
        [ 0.3800,  0.3870,  0.2539]], requires_grad=True)
tensor([1.4021, 0.2339], requires_grad=True)


In [31]:
# calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5037.5518, grad_fn=<DivBackward0>)


In [40]:
# train for 100 epochs
for i in range(1000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [41]:
# calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1.2437, grad_fn=<DivBackward0>)


In [42]:
# predictions
print(preds)
print(targets)

tensor([[ 57.4035,  70.4473],
        [ 82.0288,  99.8120],
        [118.7193, 134.6886],
        [ 21.0712,  37.4977],
        [101.8928, 117.4092]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
